### ISSUE TITLE
Invalid value for "action_file": Path "actions.yml" does not exist.

### ISSUE THREAD

**Issue by emersonramos** [bobrik/docker-curator#18]
Hi,

curator don't execute with my yml file. How I have to use the command? I used:

docker run --rm bobrik/curator:5.1.1 --dry-run actions.yml

docker run --rm bobrik/curator:5.1.1 --dry-run /var/actions.yml

I have same error: Invalid value for "action_file": Path "actions.yml" does not exist.

**Comment by bobrik** [comment]
You need to bind-mount your file into container:

```
-w $(pwd) -v $(pwd):$(pwd)
```
