### ISSUE TITLE
how to pass in config files 

### ISSUE THREAD

**Issue by lukeshaughnessy** [bobrik/docker-curator#30]
I try this command:
 docker run --rm bobrik/curator:5.4.0 --config ./curator.yml
Usage: curator [OPTIONS] ACTION_FILE

Error: Invalid value for "--config": Path "./curator.yml" does not exist.

The curator.yml file is there.

**Comment by bobrik** [comment]
You need to bind-mount `curator.yml` from the host:

```
docker run --rm -v $(pwd):$(pwd) -w $(pwd) bobrik/curator:5.4.0 --config ./curator.yml
```

* https://docs.docker.com/storage/volumes/
