### ISSUE TITLE
Upgrade to 5.5.0

### ISSUE THREAD

**Issue by deiwin** [bobrik/docker-curator#31]
[5.5.0](https://github.com/elastic/curator/releases/tag/v5.5.0) was released recently. It has some helpful fixes.

**Comment by deiwin** [comment]
I would create a PR myself, but just upgrading the version in the `Dockerfile` doesn't work - it complains about missing packages. I'm currently using a custom version of the dockerfile that explicitly installs [the pip packages from curator's `setup.py`](https://github.com/elastic/curator/blob/53d32bc1b28717774149afe4bc481af6e930b814/setup.py#L25-L29) before installing curator. This seems to work, but I don't know if it's the correct approach.

**Comment by bobrik** [comment]
Can you create a ticket for curator? Just `pip install` should work out of the box and not require anything extra.

**Comment by deiwin** [comment]
Looks like it's already [reported](https://github.com/elastic/curator/issues/1183) and fixed. Creating a PR for upgrade.
