### ISSUE TITLE
Unable to run curator,

### ISSUE THREAD

**Issue by RameshRM** [bobrik/docker-curator#33]
Hi ,

Can you add me an example , I am constantly getting `Action file` missing with `--config` param

Thx

**Comment by elpado** [comment]
Hi,

assuming that your aconfig/action files are in the current directory from where you want to call curator, then:

`docker run --rm -v $(pwd):/my-config bobrik/curator:latest --config /my-config/config.yml --dry-run /my-config/actions.yml`

This way you map the current directory to the container at "/my-config" and curator can load your config/action files.

Best
eL
