### ISSUE TITLE
How do I set the config file and action files?

### ISSUE THREAD

**Issue by jjtdepaul** [bobrik/docker-curator#37]
Do I have to copy the config.yml file into the container or do I somehow mount this file using docker volume command?    

Similarly, how do I specify the action.yml command input parameter?

**Comment by jphuynh** [comment]
Yes the most straightforward way would be using Volumes.

Let's say that you have `config.yml` and `action.yml` in the working directory.

You can run curator with the following command: 

`docker run -v$PWD:/tmp  bobrik/curator:5.6.0 --config /tmp/config.yml /tmp/action.yml`

**Comment by jjtdepaul** [comment]
I've exported env variable `HERE` and tried to run the curator with the file below, but I keep getting an error... 

PS C:\...\test\utils> type testconfig.yml
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - 127.0.0.1
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']

PS C:\...\test\utils> docker run -v $HERE :/tmp bobrik/curator --config /tmp/testconfig.yml /tmp/action-daily.yml
Usage: curator [OPTIONS] ACTION_FILE

Error: Invalid value for "--config": Path "/tmp/testconfig.yml" does not exist.
PS C:\myUbuntu18\rootfs\home\jdepaul\repos\curator\test\utils>

**Comment by jjtdepaul** [comment]
ja006652@DG41BHD12 /cygdrive/c/myUbuntu18/rootfs/home/jdepaul/repos/curator/test/utils
$ docker run -v $PWD:/tmp bobrik/curator --config /tmp/testconfig.yml /tmp/actions-daily.yml
Usage: curator [OPTIONS] ACTION_FILE
Error: Invalid value for "--config": Path "/tmp/testconfig.yml" does not exist.

ja006652@DG41BHD12 /cygdrive/c/myUbuntu18/rootfs/home/jdepaul/repos/curator/test/utils
$ ls -la | grep testconfig.yml
-rwxrwxr-x+ 1 ja006652 Domain Users   388 Mar 13 14:58 testconfig.yml


And when I explored the container mounts, I see this set correctly:
--------------------------------------------------------
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/cygdrive/c/myUbuntu18/rootfs/home/jdepaul/repos/curator/test/utils",
                "Destination": "/conf",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }

**Comment by jjtdepaul** [comment]
Thank you very much jphuynh!
